name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: docker.io/psedoc/anyhttp:1.1
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure CMake
      run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo
      
    - name: Build
      run: cmake --build build --parallel
      
    - name: Run tests with CTest
      run: ctest --test-dir build --output-on-failure
      
    - name: Run test_all for JUnit XML (optional)
      run: |
        if [ -f build/test/test_all ]; then
          mkdir -p build/test-results
          build/test/test_all --gtest_output=xml:build/test-results/test_all.xml || true
        fi
      
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          build/Testing/
          build/test-results/